language: ruby

env: CODECLIMATE_REPO_TOKEN=9fc29ca5d34246c79a8477ba030535a4c0f5a078a7304ea5f88b9cedc1cb9b7c

rvm:
  - 2.0.0
  - 2.1.2
  - jruby-19mode
  - rbx-2

branches:
  only:
    - master
    - develop

notifications:
  recipients:
    - jeffnyman@gmail.com

matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-19mode